//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.30 at 10:29:36 PM MSK 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetChatUserInfoRequest }
     * 
     */
    public GetChatUserInfoRequest createGetChatUserInfoRequest() {
        return new GetChatUserInfoRequest();
    }

    /**
     * Create an instance of {@link GetChatUserInfoResponse }
     * 
     */
    public GetChatUserInfoResponse createGetChatUserInfoResponse() {
        return new GetChatUserInfoResponse();
    }

    /**
     * Create an instance of {@link UserInfoDTO }
     * 
     */
    public UserInfoDTO createUserInfoDTO() {
        return new UserInfoDTO();
    }

    /**
     * Create an instance of {@link GetUserInfoResponse }
     * 
     */
    public GetUserInfoResponse createGetUserInfoResponse() {
        return new GetUserInfoResponse();
    }

    /**
     * Create an instance of {@link GetUserInfoRequest }
     * 
     */
    public GetUserInfoRequest createGetUserInfoRequest() {
        return new GetUserInfoRequest();
    }

    /**
     * Create an instance of {@link GetUserChatIdResponse }
     * 
     */
    public GetUserChatIdResponse createGetUserChatIdResponse() {
        return new GetUserChatIdResponse();
    }

    /**
     * Create an instance of {@link GetUserChatIdRequest }
     * 
     */
    public GetUserChatIdRequest createGetUserChatIdRequest() {
        return new GetUserChatIdRequest();
    }

    /**
     * Create an instance of {@link SaveUserInfoResponse }
     * 
     */
    public SaveUserInfoResponse createSaveUserInfoResponse() {
        return new SaveUserInfoResponse();
    }

    /**
     * Create an instance of {@link SaveUserInfoRequest }
     * 
     */
    public SaveUserInfoRequest createSaveUserInfoRequest() {
        return new SaveUserInfoRequest();
    }

}
