//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.07 at 01:51:50 AM MSK 
//


package io.spring.guides.gs_producing_web_service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chatId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="newChatName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userLoginsToAdd" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="userLoginsToDelete" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chatId",
    "newChatName",
    "userLoginsToAdd",
    "userLoginsToDelete"
})
@XmlRootElement(name = "updateChatRequest")
public class UpdateChatRequest {

    protected long chatId;
    @XmlElement(required = true)
    protected String newChatName;
    protected List<String> userLoginsToAdd;
    protected List<String> userLoginsToDelete;

    /**
     * Gets the value of the chatId property.
     * 
     */
    public long getChatId() {
        return chatId;
    }

    /**
     * Sets the value of the chatId property.
     * 
     */
    public void setChatId(long value) {
        this.chatId = value;
    }

    /**
     * Gets the value of the newChatName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewChatName() {
        return newChatName;
    }

    /**
     * Sets the value of the newChatName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewChatName(String value) {
        this.newChatName = value;
    }

    /**
     * Gets the value of the userLoginsToAdd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userLoginsToAdd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserLoginsToAdd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUserLoginsToAdd() {
        if (userLoginsToAdd == null) {
            userLoginsToAdd = new ArrayList<String>();
        }
        return this.userLoginsToAdd;
    }

    /**
     * Gets the value of the userLoginsToDelete property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userLoginsToDelete property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserLoginsToDelete().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUserLoginsToDelete() {
        if (userLoginsToDelete == null) {
            userLoginsToDelete = new ArrayList<String>();
        }
        return this.userLoginsToDelete;
    }

}
